### ISSUE TITLE
[Server] Startup 110,386 in Server_world (CIRCULAR) and similar

### ISSUE THREAD

**Issue by TwoLeggedCat** [TwoLeggedCat/MinecraftIssueTracking#4]
Log from Birch#2722:

```
20.06 15:27:37 [Server] Startup 110,386 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 113,394 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 124,383 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 110,385 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 124,387 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 123,382 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 119,394 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 112,394 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 109,394 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 119,389 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 110,394 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 116,397 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 115,391 in Server_world:
20.06 15:27:37 [Server] Startup 116,392 in Server_world (CIRCULAR)
20.06 15:27:37 [Server] Startup 123,399 in Server_world (CIRCULAR)
```

Also reported by Seren541#7353

**Comment by TwoLeggedCat** [comment]
https://mcpaste.io/fd0ef1735fad6dd1 also from Birch#2722

**Comment by TwoLeggedCat** [comment]
Radek#7423 said they have the same problem

**Comment by TwoLeggedCat** [comment]
note to anyone reading: while it may be the same cause, it is not the same error that is already documented, as that one was a different format during a thread dump, while this is thrown during startup

**Comment by ghost** [comment]
Yes, it got so bad to the point where it was crashing every couple hours. I had to eventually revert to spigot. I could send my own log here if that would help.

**Comment by TwoLeggedCat** [comment]
@Seren541 I'm sort of hoping this gets resolved along with #5910 (Paper's repo, not linking to avoid it showing up as mentioned), and I've also been unable to reproduce this one. Just in case, I should tell you this repo has nothing to do with the PaperMC organization and is practically just my own notepad (I'm also curious as to how you even found it). You can post your log if you want, but I doubt it would be enough information to reproduce it as none of the other logs have been.

**Comment by ghost** [comment]
Yeah I've seen that thread too, and ik this is not official. Saw this linked in some other thread, but I thought it was closed? I'm surprised this isn't a super common bug, as it was literally non stop for me. Somethings wrong when spigot is performing way better than paper.

**Comment by TwoLeggedCat** [comment]
This appears to have vanished from existence. @Seren541, before I close?

**Comment by ghost** [comment]
Sure, go ahead.
